### PR TITLE
Sync with @balthisar repo (inkscape 1.0 compatibility)

### PR DESCRIPTION
**Pull request by chepo92**

### CODE REVIEW

**Comment by arpruss** [comment]
Does it still work with earlier versions?

**Comment by chepo92** [comment]
Will need to check, if not maybe merge it in a new branch

**Comment by arpruss** [comment]
Does this need to be done at all? I copied the old extension to a 1.0 extensions folder and they seemed to work fine.

**Comment by chepo92** [comment]
Looking at the diff, I think the major difference is line 456 in gcodeplot (if pen != 1:), as python complains when using "is not"

**Comment by arpruss** [comment]
That was fixed in an earlier patch I think.

**Comment by chepo92** [comment]
it seems so, then closing this PR

**Pull request closed without merging**
